using System.Diagnostics;

namespace ClaudeLauncher.Sessions;

/// <summary>
/// Opens a Windows Terminal pane running Claude, while the launcher stays up.
///
/// The wrapper does the same thing at exit time in PowerShell; this is the
/// resident path, used by the terminal wall. Both write the same kind of
/// startup script, because putting the config dir and the working directory in
/// a file avoids nesting quotes inside a wt command line.
/// </summary>
public static class PaneLauncher
{
    /// <summary>
    /// Opens a pane running Claude. With <paramref name="resumeSessionId"/> the
    /// pane picks up an existing conversation, which is how a chat session is
    /// handed over to a real terminal.
    /// </summary>
    public static bool Split(ProfileEntry profile, string projectPath, bool vertical, bool remoteControl,
        out string error, string? resumeSessionId = null)
    {
        error = string.Empty;

        try
        {
            var configDir = StateStore.ExpandHome(profile.ConfigDir);
            var script = WriteStartupScript(configDir, projectPath, remoteControl, resumeSessionId);

            var info = new ProcessStartInfo("wt.exe") { UseShellExecute = true };

            // -w 0 targets the window we are in; outside Windows Terminal there
            // is none, so ask for a new one.
            info.ArgumentList.Add("-w");
            info.ArgumentList.Add(Environment.GetEnvironmentVariable("WT_SESSION") is null ? "new" : "0");
            info.ArgumentList.Add("split-pane");
            info.ArgumentList.Add(vertical ? "-V" : "-H");
            info.ArgumentList.Add("-d");
            info.ArgumentList.Add(TrimTrailingSeparator(projectPath));
            info.ArgumentList.Add("--title");
            info.ArgumentList.Add($"{profile.DisplayIcon} {Path.GetFileName(projectPath.TrimEnd('\\', '/'))}");
            info.ArgumentList.Add(Shell());
            info.ArgumentList.Add("-NoExit");
            info.ArgumentList.Add("-File");
            info.ArgumentList.Add(script);

            Process.Start(info);
            return true;
        }
        catch (Exception ex)
        {
            error = ex.Message;
            return false;
        }
    }

    private static string Shell() =>
        File.Exists(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),
            "PowerShell", "7", "pwsh.exe"))
            ? "pwsh.exe"
            : "powershell.exe";

    /// <summary>
    /// A trailing backslash before a closing quote escapes it for
    /// CommandLineToArgvW, so drop it - except on a bare drive root.
    /// </summary>
    private static string TrimTrailingSeparator(string path) =>
        path.Length > 3 && (path.EndsWith('\\') || path.EndsWith('/')) ? path.TrimEnd('\\', '/') : path;

    private static string WriteStartupScript(string configDir, string projectPath, bool remoteControl,
        string? resumeSessionId = null)
    {
        var directory = Path.Combine(StateStore.DataDir, "panes");
        Directory.CreateDirectory(directory);

        foreach (var stale in new DirectoryInfo(directory).GetFiles("pane-*.ps1"))
        {
            if (stale.LastWriteTimeUtc < DateTime.UtcNow.AddDays(-2))
            {
                try { stale.Delete(); } catch { /* disposable either way */ }
            }
        }

        var file = Path.Combine(directory, $"pane-{Guid.NewGuid():N}.ps1");

        var name = Path.GetFileName(projectPath.TrimEnd('\\', '/'));
        var claude = "claude";
        if (!string.IsNullOrWhiteSpace(resumeSessionId)) claude += $" --resume {Literal(resumeSessionId!)}";
        if (remoteControl) claude += $" --remote-control {Literal(name)}";

        var lines = new[]
        {
            "# Generated by claude-launcher. Safe to delete.",
            $"$env:CLAUDE_CONFIG_DIR = {Literal(configDir)}",
            $"Set-Location -LiteralPath {Literal(projectPath)}",
            string.Empty,
            "if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {",
            "    Write-Host \"claude was not found on PATH in this pane.\" -ForegroundColor Red",
            "    return",
            "}",
            string.Empty,
            claude,
            "Write-Host \"\"",
            "Write-Host \"Claude exited. This pane stays open - close it with exit.\" -ForegroundColor DarkGray"
        };

        File.WriteAllLines(file, lines);
        return file;
    }

    /// <summary>Single-quoted PowerShell literal; doubling is how a quote is escaped there.</summary>
    private static string Literal(string value) => "'" + value.Replace("'", "''") + "'";
}
